# Generated by Django 5.2.17 on 2026-09-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='authtoken.token')),
            ],
        ),
    ]
